### ISSUE TITLE
Possibility to unpublish solutions

### ISSUE THREAD

**Issue by mhils** [CaptureAmerica/writeups#1]
Hi @CaptureAmerica!

Thank you for your excellent CTF write-ups! 😃  I'm the author of the Honeynet Workshop CTF you participated in. We would like to re-use the easier challenges we built for teaching at the University of Innsbruck. Unfortunately, if our students search for parts of the challenge, your write-ups would turn up and they can just copy solutions. Would it be possible for you to take down the Honeynet write-ups? I understand the value of having write-ups online, but it'd be fantastic if we could keep teaching this.

Thank you!

**Comment by CaptureAmerica** [comment]
Sure. I can totally understand and totally ok with it. I removed the contents from the writeup page. I assume that you will have the same kind of CTF every year, so I will keep it removed (e.g. will not put it back). Thanks!

CaptureAmerica

________________________________
差出人: Maximilian Hils <notifications@github.com>
送信日時: 2020年4月30日 23:16
宛先: CaptureAmerica/writeups <writeups@noreply.github.com>
CC: CaptureAmerica <fwht6361@hotmail.com>; Mention <mention@noreply.github.com>
件名: [CaptureAmerica/writeups] Possibility to unpublish solutions (#1)


Hi @CaptureAmerica<https://github.com/CaptureAmerica>!

Thank you for your excellent CTF write-ups! 😃 I'm the author of the Honeynet Workshop CTF you participated in. We would like to re-use the easier challenges we built for teaching at the University of Innsbruck. Unfortunately, if our students search for parts of the challenge, your write-ups would turn up and they can just copy solutions. Would it be possible for you to take down the Honeynet write-ups? I understand the value of having write-ups online, but it'd be fantastic if we could keep teaching this.

Thank you!

**Comment by mhils** [comment]
Thank you so much for your understanding! 🍰 😃
